<?php
$helper = Mage::helper("webgraphee_ogmeta");
if (!$helper->isOgMetaEnabled()) {
    return;
}
$image = $helper->getOgImage();
$siteName = $helper->getSiteName();
?>

<!-- OG META Data --> 
<meta property="og:title" content="<?php echo $this->getLayout()->getBlock('head')->getTitle(); ?>" />
<meta property="og:site_name" content="<?php echo $siteName; ?>" />
<meta property="og:type" content="article" />
<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl(); ?>" />
<meta property="og:image" content="<?php echo $image; ?>" />
<meta property="og:description" content="<?php echo $this->getLayout()->getBlock('head')->getDescription(); ?>" />

